spring.config.activate.on-profile=prod

spring.datasource.url=${POSTGRESQL_URL}
spring.datasource.username=${POSTGRESQL_USER}
spring.datasource.password=${POSTGRESQL_PASSWORD}


management.endpoint.health.show-details=never

logging.level.root=WARN