spring.config.activate.on-profile=staging

spring.datasource.url=${POSTGRESQL_URL}
spring.datasource.username=${POSTGRESQL_USER}
spring.datasource.password=${POSTGRESQL_PASSWORD}




logging.level.org.springframework=INFO
logging.level.com.plcoding=DEBUG